apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce
  namespace: dev
  labels:
    app: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce
  template:
    metadata:
      labels:
        app: ecommerce
    spec:
      containers:
        - image: olfarejeb/front-ecommerce:__IMAGE_TAG__
          imagePullPolicy: Always
          name: ecommerce
          ports:
            - containerPort: 80
          resources:
              requests:
                cpu: 100m
