kind: Service
apiVersion: v1
metadata:
  name: ecommerce 
  namespace: dev 
  labels:
    app: ecommerce 
spec:
  type: NodePort
  selector:
    app: ecommerce 
  ports:
    - port: 80
      name: http
      targetPort: 80
      nodePort: 30007
